### ISSUE TITLE
Review parse-sheet

### ISSUE THREAD

**Issue by miakh** [vkh-cr/av-app#13]

**Comment by Gldkslfmsd** [comment]
asi to je duplicitní se #14

**Comment by miakh** [comment]
@Gldkslfmsd hoď si prosím tu PR do "ready for review". Toto je task pro Marka.

**Comment by marekm294** [comment]
proc mam review python? Me znalosti pythonu jsou velice low

**Comment by Gldkslfmsd** [comment]
tohle review udělal Michal -- viz commenty u  #14
