### ISSUE TITLE
HomePage: Ikonka s avatarem a se jménem + logo AV 2023

### ISSUE THREAD

**Issue by EsterKo** [vkh-cr/av-app#24]
Ikonka s avaterem a jménem přes kterou se jde prokliknout na uživatelské nastavení.
V případě, že uživatel nebude přihlášený, bude tam ikonka/tlačítko "přihlásit se".

Logo AV v opačné části než je ikonka s avatarem, viz připravený design od Marušky.

Pro ikonku s avatarem lze momentálně použít Icons.account_circle_round

**Comment by miakh** [comment]
![Image](https://user-images.githubusercontent.com/2659269/235296545-88e39929-cc42-4644-a407-2fa9de68f650.png)
