### ISSUE TITLE
MapPage: konkrétní ikonky na mapu

### ISSUE THREAD

**Issue by EsterKo** [vkh-cr/av-app#25]
Podívat se na kategorie typů ikonek zde: https://docs.google.com/spreadsheets/d/1l4NHsLlahVUdRjVEe48X_ogHTLNJ7Nvt/edit#gid=140715753 nebo přímo v Supabase a odsouhlasit si kategorie. 

Následně zadat tvorbu ikonek.

**Comment by miakh** [comment]
tyto typy:

- bankomat
- kostel/kaple
- kavárna
- vinárna
- recepce ... ekvivalent registrace
- jídlo
- sport (hřiště)
- jiné (náměstí, zahrada, velehradské infocentrum, místa před) - bez ikonky
- ubytování
- kříž (velehradský)

slovník (v tabulce se používá anglický název, při výběru typu se používá český - uvnitř aplikace)

atm - bankomat
church - kostel/kaple
coffee - kavárna
wine - vinárna
reception - recepce
food - jídlo
sport - sport
accomodation - ubytování
cross - kříž
other - jiné

 @EsterKo Může být?

**Comment by EsterKo** [comment]
Odkaz na aktuální seznam ikonek -> (sloupce G až H): https://docs.google.com/spreadsheets/d/1l4NHsLlahVUdRjVEe48X_ogHTLNJ7Nvt/edit#gid=2141157389
